INSERT INTO pracownicy(towar, cel, pochodzenie, termin, rejestracha_samochodu, specialne_warunki, id_pracownika, id_klienta, id_kontenera)
VALUES
('melale przemysłowe', 'Siemianowice Śląskie', 'Katowice', '04-01-2020', 'rej', 'wymaga oczenikania', 'prac', '1', 'kon'),
('AGD', 'Sosnowiec', 'Sosnowiec', '04-01-2020', 'rej', 'wymaga oczenikania', 'prac', '1', 'kon'),
('melale przemysłowe', 'Sosnowiec', 'Katowice', '05-01-2020', 'rej', '', 'prac', '2', 'kon'),
('części samolotowe', 'Ostrowiec Świętokrzyski', 'Katowice', '05-01-2020', 'rej', '', 'prac', '3', 'kon'),
('papier', 'Bydgoszcz', 'Gliwice', '06-01-2020', 'rej', '', 'prac', '4', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Gliwice', 'term', 'rej', '', 'prac', '5', 'kon'),
('części do maszyn budowlanych', 'Gliwice', 'Bielsko-Biala', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '6', 'kon'),
('plastiki', 'Bielsko-Biala', 'Katowice', 'term', 'rej', '', 'prac', '7', 'kon'),
('szkło', 'Katowice', 'Radom', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '8', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Dąbrowa Górnicza', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '9', 'kon'),
('AGD', 'Radomsko', 'Jelenia Góra', 'term', 'rej', '', 'prac', '10', 'kon'),
('części samochodowe', 'Częstochowa', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '11', 'kon'),
('szkło', 'Jaworzno', 'Tarnobrzeg', 'term', 'rej', '', 'prac', '12', 'kon'),
('alkochol', 'Gliwice', 'Wroclaw', 'term', 'rej', '', 'prac', '13', 'kon'),
('melale przemysłowe', 'Chorzów', 'Wejherowo', 'term', 'rej', '', 'prac', '14', 'kon'),
('części do maszyn budowlanych', 'Gliwice', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '15', 'kon'),
('mrożonki', 'Ostrolęka', 'Przemyśl', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '16', 'kon'),
('szkło', 'Jaworzno', 'Tarnów', 'term', 'rej', '', 'prac', '17', 'kon'),
('części samochodowe', 'Ruda Śląska', 'Konin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '18', 'kon'),
('części samochodowe', 'Plock', 'Nowy Sącz', 'term', 'rej', '', 'prac', '19', 'kon'),
('części samochodowe', 'Jaworzno', 'Ruda Śląska', 'term', 'rej', '', 'prac', '20', 'kon'),
('szkło', 'lódź', 'Skarżysko-Kamienna', 'term', 'rej', '', 'prac', '21', 'kon'),
('mrożonki', 'Gliwice', 'Szczecin', 'term', 'rej', '', 'prac', '22', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Skarżysko-Kamienna', 'Gdańsk', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '23', 'kon'),
('warzywa', 'Nowy Sącz', 'Jelenia Góra', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '24', 'kon'),
('melale przemysłowe', 'Gorzów Wielkopolski', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '25', 'kon'),
('części samolotowe', 'Żory', 'Gliwice', 'term', 'rej', '', 'prac', '26', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Jaworzno', 'Bialystok', 'term', 'rej', '', 'prac', '27', 'kon'),
('części do maszyn budowlanych', 'Sosnowiec', 'Gliwice', 'term', 'rej', '', 'prac', '28', 'kon'),
('części samochodowe', 'Ruda Śląska', 'Opole', 'term', 'rej', '', 'prac', '29', 'kon'),
('części do maszyn budowlanych', 'Glogów', 'Tczew', 'term', 'rej', '', 'prac', '30', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Ruda Śląska', 'Ruda Śląska', 'term', 'rej', '', 'prac', '31', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '32', 'kon'),
('części samochodowe', 'Ostrowiec Świętokrzyski', 'Katowice', 'term', 'rej', '', 'prac', '33', 'kon'),
('alkochol', 'Inowroclaw', 'Sosnowiec', 'term', 'rej', '', 'prac', '34', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Bielsko-Biala', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '35', 'kon'),
('napoje', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '36', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Ostrowiec Świętokrzyski', 'Bielsko-Biala', 'term', 'rej', 'wymaga oczenikania', 'prac', '37', 'kon'),
('warzywa', 'Legnica', 'Gdańsk', 'term', 'rej', 'wymaga oczenikania', 'prac', '38', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '39', 'kon'),
('napoje', 'Dąbrowa Górnicza', 'Gliwice', 'term', 'rej', '', 'prac', '40', 'kon'),
('melale przemysłowe', 'Racibórz', 'Wodzislaw Śląski', 'term', 'rej', '', 'prac', '41', 'kon'),
('mrożonki', 'Katowice', 'Pulawy', 'term', 'rej', '', 'prac', '42', 'kon'),
('warzywa', 'Zawiercie', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '43', 'kon'),
('napoje', 'Bielsko-Biala', 'Lubin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '44', 'kon'),
('napoje', 'Katowice', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '45', 'kon'),
('części samolotowe', 'Ruda Śląska', 'Krosno', 'term', 'rej', '', 'prac', '46', 'kon'),
('papier', 'Elbląg', 'Jaworzno', 'term', 'rej', '', 'prac', '47', 'kon'),
('AGD', 'Ostrowiec Świętokrzyski', 'Sosnowiec', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '48', 'kon'),
('sprzęt budowlany', 'Katowice', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '49', 'kon'),
('alkochol', 'Szczecin', 'Katowice', 'term', 'rej', '', 'prac', '50', 'kon'),
('sprzęt budowlany', 'Sosnowiec', 'Gorzów Wielkopolski', 'term', 'rej', '', 'prac', '51', 'kon'),
('warzywa', 'Sosnowiec', 'Sosnowiec', 'term', 'rej', '', 'prac', '52', 'kon'),
('szkło', 'Piotrków', 'Katowice', 'term', 'rej', '', 'prac', '53', 'kon'),
('melale przemysłowe', 'Konin', 'Katowice', 'term', 'rej', '', 'prac', '54', 'kon'),
('części do maszyn budowlanych', 'Slupsk', 'Olsztyn', 'term', 'rej', '', 'prac', '55', 'kon'),
('szkło', 'Będzin', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '56', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Gliwice', 'Pulawy', 'term', 'rej', '', 'prac', '57', 'kon'),
('napoje', 'Sosnowiec', 'Katowice', 'term', 'rej', '', 'prac', '58', 'kon'),
('plastiki', 'Jaworzno', 'Biala Podlaska', 'term', 'rej', 'wymaga oczenikania', 'prac', '59', 'kon'),
('plastiki', 'Stargard', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '60', 'kon'),
('alkochol', 'Gliwice', 'Plock', 'term', 'rej', '', 'prac', '61', 'kon'),
('AGD', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '62', 'kon'),
('części samolotowe', 'Katowice', 'Ruda Śląska', 'term', 'rej', '', 'prac', '63', 'kon'),
('AGD', 'Jaworzno', 'Katowice', 'term', 'rej', '', 'prac', '64', 'kon'),
('sprzęt budowlany', 'Katowice', 'Dąbrowa Górnicza', 'term', 'rej', 'wymaga oczenikania', 'prac', '65', 'kon'),
('napoje', 'Katowice', 'Będzin', 'term', 'rej', '', 'prac', '66', 'kon'),
('RTV', 'Kędzierzyn-Koźle', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '67', 'kon'),
('części samochodowe', 'Bielsko-Biala', 'Pulawy', 'term', 'rej', '', 'prac', '68', 'kon'),
('AGD', 'Pulawy', 'Częstochowa', 'term', 'rej', '', 'prac', '69', 'kon'),
('napoje', 'Jaworzno', 'Elk', 'term', 'rej', 'przewóz specialny', 'prac', '70', 'kon'),
('papier', 'Będzin', 'Katowice', 'term', 'rej', '', 'prac', '71', 'kon'),
('sprzęt budowlany', 'Jaworzno', 'Nowy Sącz', 'term', 'rej', '', 'prac', '72', 'kon'),
('szkło', 'Dębica', 'Wodzislaw Śląski', 'term', 'rej', 'wymaga oczenikania', 'prac', '73', 'kon'),
('drewno', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '74', 'kon'),
('szkło', 'Gliwice', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '75', 'kon'),
('plastiki', 'Wejherowo', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '76', 'kon'),
('drewno', 'Sosnowiec', 'Dębica', 'term', 'rej', 'wymaga oczenikania', 'prac', '77', 'kon'),
('melale przemysłowe', 'Lublin', 'Elbląg', 'term', 'rej', '', 'prac', '78', 'kon'),
('alkochol', 'Lublin', 'lódź', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '79', 'kon'),
('mrożonki', 'Jaworzno', 'Gliwice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '80', 'kon'),
('warzywa', 'Zamość', 'Gdynia', 'term', 'rej', '', 'prac', '81', 'kon'),
('szkło', 'Katowice', 'Piaseczno', 'term', 'rej', '', 'prac', '82', 'kon'),
('części samochodowe', 'Katowice', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '83', 'kon'),
('napoje', 'Katowice', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '84', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Zielona Góra', 'Poznań', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '85', 'kon'),
('AGD', 'Lublin', 'Rumia', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '86', 'kon'),
('melale przemysłowe', 'Tomaszów Mazowiecki', 'Ruda Śląska', 'term', 'rej', '', 'prac', '87', 'kon'),
('melale przemysłowe', 'Myslowice', 'Bialystok', 'term', 'rej', 'wymaga oczenikania', 'prac', '88', 'kon'),
('plastiki', 'Gliwice', 'Ruda Śląska', 'term', 'rej', '', 'prac', '89', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '90', 'kon'),
('napoje', 'Chelm', 'Lomża', 'term', 'rej', '', 'prac', '91', 'kon'),
('melale przemysłowe', 'Jaworzno', 'Gniezno', 'term', 'rej', '', 'prac', '92', 'kon'),
('szkło', 'Katowice', 'Suwalki', 'term', 'rej', 'wymaga oczenikania', 'prac', '93', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Ostrolęka', 'Sosnowiec', 'term', 'rej', '', 'prac', '94', 'kon'),
('części samochodowe', 'Pabianice', 'Olsztyn', 'term', 'rej', 'wymaga oczenikania', 'prac', '95', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Siemianowice Śląskie', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '96', 'kon'),
('mrożonki', 'Tomaszów Mazowiecki', 'Skierniewice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '97', 'kon'),
('AGD', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '98', 'kon'),
('alkochol', 'Skarżysko-Kamienna', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '99', 'kon'),
('drewno', 'Jastrzębie-Zdrój', 'Gdańsk', 'term', 'rej', 'wymaga oczenikania', 'prac', '100', 'kon'),
('mrożonki', 'Sosnowiec', 'Jaworzno', 'term', 'rej', '', 'prac', '101', 'kon'),
('plastiki', 'Olsztyn', 'Katowice', 'term', 'rej', '', 'prac', '102', 'kon'),
('części samolotowe', 'Olsztyn', 'Sosnowiec', 'term', 'rej', '', 'prac', '103', 'kon'),
('plastiki', 'Ruda Śląska', 'Kielce', 'term', 'rej', '', 'prac', '104', 'kon'),
('części samolotowe', 'Siedlce', 'Katowice', 'term', 'rej', '', 'prac', '105', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Siemianowice Śląskie', 'Dąbrowa Górnicza', 'term', 'rej', '', 'prac', '106', 'kon'),
('mrożonki', 'Ruda Śląska', 'Toruń', 'term', 'rej', 'wymaga oczenikania', 'prac', '107', 'kon'),
('sprzęt budowlany', 'Ruda Śląska', 'Piekary Śląskie', 'term', 'rej', '', 'prac', '108', 'kon'),
('sprzęt budowlany', 'Grudziądz', 'Dąbrowa Górnicza', 'term', 'rej', '', 'prac', '109', 'kon'),
('warzywa', 'Legnica', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '110', 'kon'),
('papier', 'Tczew', 'Świętochlowice', 'term', 'rej', '', 'prac', '111', 'kon'),
('mrożonki', 'Gdynia', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '112', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Gorzów Wielkopolski', 'Inowroclaw', 'term', 'rej', 'przewóz specialny', 'prac', '113', 'kon'),
('RTV', 'Bielsko-Biala', 'Katowice', 'term', 'rej', '', 'prac', '114', 'kon'),
('sprzęt budowlany', 'Ruda Śląska', 'Katowice', 'term', 'rej', 'przewóz specialny', 'prac', '115', 'kon'),
('mrożonki', 'Bytom', 'Gdynia', 'term', 'rej', '', 'prac', '116', 'kon'),
('RTV', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '117', 'kon'),
('plastiki', 'Kraków', 'Zabrze', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '118', 'kon'),
('RTV', 'Ruda Śląska', 'Kędzierzyn-Koźle', 'term', 'rej', 'wymaga oczenikania', 'prac', '119', 'kon'),
('części samochodowe', 'Gliwice', 'Bialystok', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '120', 'kon'),
('warzywa', 'Walbrzych', 'Wroclaw', 'term', 'rej', '', 'prac', '121', 'kon'),
('sprzęt budowlany', 'Gliwice', 'Jaworzno', 'term', 'rej', '', 'prac', '122', 'kon'),
('szkło', 'Gdynia', 'Plock', 'term', 'rej', '', 'prac', '123', 'kon'),
('RTV', 'Jaworzno', 'Jaworzno', 'term', 'rej', '', 'prac', '124', 'kon'),
('AGD', 'Gliwice', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '125', 'kon'),
('drewno', 'Świętochlowice', 'Siemianowice Śląskie', 'term', 'rej', 'wymaga oczenikania', 'prac', '126', 'kon'),
('warzywa', 'Sosnowiec', 'Wodzislaw Śląski', 'term', 'rej', '', 'prac', '127', 'kon'),
('AGD', 'Sosnowiec', 'Zielona Góra', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '128', 'kon'),
('szkło', 'Katowice', 'Sosnowiec', 'term', 'rej', 'przewóz specialny', 'prac', '129', 'kon'),
('melale przemysłowe', 'Kraków', 'Suwalki', 'term', 'rej', '', 'prac', '130', 'kon'),
('RTV', 'Myslowice', 'Biala Podlaska', 'term', 'rej', 'wymaga oczenikania', 'prac', '131', 'kon'),
('melale przemysłowe', 'Siemianowice Śląskie', 'Racibórz', 'term', 'rej', '', 'prac', '132', 'kon'),
('części samochodowe', 'Tarnów', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '133', 'kon'),
('papier', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '134', 'kon'),
('sprzęt budowlany', 'Gliwice', 'Katowice', 'term', 'rej', 'przewóz specialny', 'prac', '135', 'kon'),
('szkło', 'Ruda Śląska', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '136', 'kon'),
('sprzęt budowlany', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '137', 'kon'),
('napoje', 'Katowice', 'Pruszków', 'term', 'rej', '', 'prac', '138', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Elbląg', 'Zielona Góra', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '139', 'kon'),
('części samolotowe', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '140', 'kon'),
('napoje', 'Katowice', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '141', 'kon'),
('warzywa', 'Kolobrzeg', 'Jastrzębie-Zdrój', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '142', 'kon'),
('AGD', 'Lublin', 'Piotrków', 'term', 'rej', '', 'prac', '143', 'kon'),
('części do maszyn budowlanych', 'Katowice', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '144', 'kon'),
('części do maszyn budowlanych', 'Inowroclaw', 'Biala Podlaska', 'term', 'rej', '', 'prac', '145', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Chorzów', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '146', 'kon'),
('papier', 'Elbląg', 'Lomża', 'term', 'rej', '', 'prac', '147', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '148', 'kon'),
('warzywa', 'Gniezno', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '149', 'kon'),
('alkochol', 'Siemianowice Śląskie', 'Warszawa', 'term', 'rej', '', 'prac', '150', 'kon'),
('szkło', 'Piotrków', 'Suwalki', 'term', 'rej', '', 'prac', '151', 'kon'),
('melale przemysłowe', 'Siemianowice Śląskie', 'Myslowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '152', 'kon'),
('części do maszyn budowlanych', 'Ruda Śląska', 'Ruda Śląska', 'term', 'rej', '', 'prac', '153', 'kon'),
('drewno', 'Rumia', 'Jaworzno', 'term', 'rej', 'wymaga oczenikania', 'prac', '154', 'kon'),
('RTV', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '155', 'kon'),
('warzywa', 'Dąbrowa Górnicza', 'Lubin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '156', 'kon'),
('części samochodowe', 'Katowice', 'Biala Podlaska', 'term', 'rej', '', 'prac', '157', 'kon'),
('mrożonki', 'Sosnowiec', 'Jaworzno', 'term', 'rej', '', 'prac', '158', 'kon'),
('papier', 'Katowice', 'Siemianowice Śląskie', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '159', 'kon'),
('części samochodowe', 'Katowice', 'Sosnowiec', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '160', 'kon'),
('części samochodowe', 'Bielsko-Biala', 'Katowice', 'term', 'rej', '', 'prac', '161', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Legionowo', 'Bytom', 'term', 'rej', '', 'prac', '162', 'kon'),
('mrożonki', 'Rzeszów', 'Żory', 'term', 'rej', 'wymaga oczenikania', 'prac', '163', 'kon'),
('RTV', 'Olsztyn', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '164', 'kon'),
('plastiki', 'Kielce', 'Ruda Śląska', 'term', 'rej', '', 'prac', '165', 'kon'),
('części do maszyn budowlanych', 'Walbrzych', 'Sosnowiec', 'term', 'rej', '', 'prac', '166', 'kon'),
('części samochodowe', 'Gliwice', 'Plock', 'term', 'rej', '', 'prac', '167', 'kon'),
('warzywa', 'Myslowice', 'Starachowice', 'term', 'rej', '', 'prac', '168', 'kon'),
('warzywa', 'Sosnowiec', 'Inowroclaw', 'term', 'rej', 'wymaga oczenikania', 'prac', '169', 'kon'),
('napoje', 'Plock', 'Glogów', 'term', 'rej', '', 'prac', '170', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Jaworzno', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '171', 'kon'),
('szkło', 'Mielec', 'Chorzów', 'term', 'rej', '', 'prac', '172', 'kon'),
('melale przemysłowe', 'Tczew', 'Piaseczno', 'term', 'rej', 'przewóz specialny', 'prac', '173', 'kon'),
('papier', 'Warszawa', 'lódź', 'term', 'rej', '', 'prac', '174', 'kon'),
('warzywa', 'Jaworzno', 'Rzeszów', 'term', 'rej', '', 'prac', '175', 'kon'),
('napoje', 'Sosnowiec', 'Katowice', 'term', 'rej', '', 'prac', '176', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Legnica', 'term', 'rej', '', 'prac', '177', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Rumia', 'Tarnów', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '178', 'kon'),
('AGD', 'Kalisz', 'Jelenia Góra', 'term', 'rej', '', 'prac', '179', 'kon'),
('RTV', 'Ruda Śląska', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '180', 'kon'),
('części samochodowe', 'Katowice', 'Stargard', 'term', 'rej', '', 'prac', '181', 'kon'),
('papier', 'Zielona Góra', 'Jaworzno', 'term', 'rej', '', 'prac', '182', 'kon'),
('alkochol', 'Ruda Śląska', 'Tarnów', 'term', 'rej', 'wymaga oczenikania', 'prac', '183', 'kon'),
('drewno', 'Ruda Śląska', 'Gorzów Wielkopolski', 'term', 'rej', '', 'prac', '184', 'kon'),
('AGD', 'Jaworzno', 'Sosnowiec', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '185', 'kon'),
('alkochol', 'Gliwice', 'Jaworzno', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '186', 'kon'),
('alkochol', 'Gorzów Wielkopolski', 'Racibórz', 'term', 'rej', '', 'prac', '187', 'kon'),
('alkochol', 'Glogów', 'Ostrowiec Świętokrzyski', 'term', 'rej', '', 'prac', '188', 'kon'),
('szkło', 'Olsztyn', 'Olsztyn', 'term', 'rej', '', 'prac', '189', 'kon'),
('RTV', 'Siemianowice Śląskie', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '190', 'kon'),
('części samochodowe', 'Bielsko-Biala', 'Piekary Śląskie', 'term', 'rej', '', 'prac', '191', 'kon'),
('napoje', 'Mielec', 'Katowice', 'term', 'rej', '', 'prac', '192', 'kon'),
('części samolotowe', 'Gliwice', 'Jaworzno', 'term', 'rej', '', 'prac', '193', 'kon'),
('drewno', 'Katowice', 'Jaworzno', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '194', 'kon'),
('AGD', 'Sosnowiec', 'Radomsko', 'term', 'rej', '', 'prac', '195', 'kon'),
('RTV', 'Opole', 'Belchatów', 'term', 'rej', '', 'prac', '196', 'kon'),
('papier', 'Radomsko', 'Gdynia', 'term', 'rej', 'wymaga oczenikania', 'prac', '197', 'kon'),
('warzywa', 'Ruda Śląska', 'Zamość', 'term', 'rej', '', 'prac', '198', 'kon'),
('części samolotowe', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '199', 'kon'),
('szkło', 'Bielsko-Biala', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '200', 'kon'),
('napoje', 'Tarnowskie Góry', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '201', 'kon'),
('warzywa', 'Piekary Śląskie', 'Gliwice', 'term', 'rej', '', 'prac', '202', 'kon'),
('papier', 'Tarnobrzeg', 'Ruda Śląska', 'term', 'rej', '', 'prac', '203', 'kon'),
('sprzęt budowlany', 'Bielsko-Biala', 'Bielsko-Biala', 'term', 'rej', '', 'prac', '204', 'kon'),
('RTV', 'Gliwice', 'Ruda Śląska', 'term', 'rej', '', 'prac', '205', 'kon'),
('AGD', 'Gliwice', 'Legionowo', 'term', 'rej', '', 'prac', '206', 'kon'),
('RTV', 'Pabianice', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '207', 'kon'),
('warzywa', 'Chelm', 'Tarnobrzeg', 'term', 'rej', '', 'prac', '208', 'kon'),
('drewno', 'Plock', 'Tomaszów Mazowiecki', 'term', 'rej', 'wymaga oczenikania', 'prac', '209', 'kon'),
('szkło', 'Skierniewice', 'Olsztyn', 'term', 'rej', 'wymaga oczenikania', 'prac', '210', 'kon'),
('AGD', 'Bialystok', 'Katowice', 'term', 'rej', '', 'prac', '211', 'kon'),
('części samolotowe', 'Grudziądz', 'Bydgoszcz', 'term', 'rej', 'wymaga oczenikania', 'prac', '212', 'kon'),
('plastiki', 'Siemianowice Śląskie', 'Sosnowiec', 'term', 'rej', '', 'prac', '213', 'kon'),
('części do maszyn budowlanych', 'Piotrków', 'Siemianowice Śląskie', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '214', 'kon'),
('plastiki', 'Ruda Śląska', 'Gliwice', 'term', 'rej', '', 'prac', '215', 'kon'),
('mrożonki', 'Elbląg', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '216', 'kon'),
('części samolotowe', 'Radom', 'Radomsko', 'term', 'rej', '', 'prac', '217', 'kon'),
('AGD', 'Glogów', 'Pabianice', 'term', 'rej', '', 'prac', '218', 'kon'),
('plastiki', 'Myslowice', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '219', 'kon'),
('napoje', 'Glogów', 'Elbląg', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '220', 'kon'),
('sprzęt budowlany', 'Katowice', 'Świdnica', 'term', 'rej', '', 'prac', '221', 'kon'),
('RTV', 'Mielec', 'Sosnowiec', 'term', 'rej', 'przewóz specialny', 'prac', '222', 'kon'),
('sprzęt budowlany', 'Kędzierzyn-Koźle', 'Siedlce', 'term', 'rej', '', 'prac', '223', 'kon'),
('AGD', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '224', 'kon'),
('plastiki', 'Katowice', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '225', 'kon'),
('AGD', 'Leszno', 'Szczecin', 'term', 'rej', '', 'prac', '226', 'kon'),
('plastiki', 'Siedlce', 'Katowice', 'term', 'rej', '', 'prac', '227', 'kon'),
('plastiki', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '228', 'kon'),
('części do maszyn budowlanych', 'Rybnik', 'Ruda Śląska', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '229', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Jelenia Góra', 'Gliwice', 'term', 'rej', '', 'prac', '230', 'kon'),
('plastiki', 'Ruda Śląska', 'Bytom', 'term', 'rej', 'wymaga oczenikania', 'prac', '231', 'kon'),
('części samolotowe', 'Siemianowice Śląskie', 'Gdańsk', 'term', 'rej', '', 'prac', '232', 'kon'),
('części samolotowe', 'Ostrowiec Świętokrzyski', 'Kalisz', 'term', 'rej', '', 'prac', '233', 'kon'),
('AGD', 'Żory', 'Sosnowiec', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '234', 'kon'),
('warzywa', 'Myslowice', 'Gliwice', 'term', 'rej', '', 'prac', '235', 'kon'),
('papier', 'Katowice', 'Opole', 'term', 'rej', '', 'prac', '236', 'kon'),
('drewno', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '237', 'kon'),
('RTV', 'Konin', 'Kielce', 'term', 'rej', '', 'prac', '238', 'kon'),
('sprzęt budowlany', 'Wroclaw', 'Ostrowiec Świętokrzyski', 'term', 'rej', '', 'prac', '239', 'kon'),
('melale przemysłowe', 'Sosnowiec', 'Katowice', 'term', 'rej', '', 'prac', '240', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Sosnowiec', 'Katowice', 'term', 'rej', '', 'prac', '241', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Ruda Śląska', 'Elbląg', 'term', 'rej', '', 'prac', '242', 'kon'),
('warzywa', 'Chorzów', 'Lomża', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '243', 'kon'),
('alkochol', 'Tychy', 'Zabrze', 'term', 'rej', '', 'prac', '244', 'kon'),
('plastiki', 'Zgierz', 'Ruda Śląska', 'term', 'rej', '', 'prac', '245', 'kon'),
('papier', 'Legionowo', 'Sosnowiec', 'term', 'rej', '', 'prac', '246', 'kon'),
('melale przemysłowe', 'Sosnowiec', 'Gliwice', 'term', 'rej', '', 'prac', '247', 'kon'),
('mrożonki', 'Katowice', 'Walbrzych', 'term', 'rej', '', 'prac', '248', 'kon'),
('AGD', 'Katowice', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '249', 'kon'),
('plastiki', 'Gliwice', 'Racibórz', 'term', 'rej', 'wymaga oczenikania', 'prac', '250', 'kon'),
('plastiki', 'Poznań', 'Krosno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '251', 'kon'),
('części do maszyn budowlanych', 'Gliwice', 'Pulawy', 'term', 'rej', '', 'prac', '252', 'kon'),
('AGD', 'Tczew', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '253', 'kon'),
('sprzęt budowlany', 'Tarnów', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '254', 'kon'),
('plastiki', 'Żory', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '255', 'kon'),
('warzywa', 'Piaseczno', 'Radomsko', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '256', 'kon'),
('części samolotowe', 'Radomsko', 'Gliwice', 'term', 'rej', '', 'prac', '257', 'kon'),
('melale przemysłowe', 'Krosno', 'Świętochlowice', 'term', 'rej', '', 'prac', '258', 'kon'),
('plastiki', 'Siemianowice Śląskie', 'Walbrzych', 'term', 'rej', 'wymaga oczenikania', 'prac', '259', 'kon'),
('części do maszyn budowlanych', 'Toruń', 'Bielsko-Biala', 'term', 'rej', '', 'prac', '260', 'kon'),
('napoje', 'Katowice', 'Radomsko', 'term', 'rej', '', 'prac', '261', 'kon'),
('części samolotowe', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '262', 'kon'),
('sprzęt budowlany', 'Gliwice', 'Bytom', 'term', 'rej', '', 'prac', '263', 'kon'),
('AGD', 'Jaworzno', 'Koszalin', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '264', 'kon'),
('części samolotowe', 'Lublin', 'Skierniewice', 'term', 'rej', '', 'prac', '265', 'kon'),
('części samolotowe', 'Zgierz', 'Zamość', 'term', 'rej', 'wymaga oczenikania', 'prac', '266', 'kon'),
('plastiki', 'Chorzów', 'Ruda Śląska', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '267', 'kon'),
('części samolotowe', 'Siemianowice Śląskie', 'Tomaszów Mazowiecki', 'term', 'rej', 'wymaga oczenikania', 'prac', '268', 'kon'),
('melale przemysłowe', 'Siemianowice Śląskie', 'Świętochlowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '269', 'kon'),
('plastiki', 'Siemianowice Śląskie', 'Ostrolęka', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '270', 'kon'),
('części do maszyn budowlanych', 'Gliwice', 'Sosnowiec', 'term', 'rej', '', 'prac', '271', 'kon'),
('RTV', 'Zamość', 'Poznań', 'term', 'rej', '', 'prac', '272', 'kon'),
('drewno', 'Chorzów', 'Jaworzno', 'term', 'rej', '', 'prac', '273', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Dębica', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '274', 'kon'),
('napoje', 'Gliwice', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '275', 'kon'),
('AGD', 'Katowice', 'Skarżysko-Kamienna', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '276', 'kon'),
('RTV', 'Siemianowice Śląskie', 'Jastrzębie-Zdrój', 'term', 'rej', 'wymaga oczenikania', 'prac', '277', 'kon'),
('papier', 'Kalisz', 'Kraków', 'term', 'rej', '', 'prac', '278', 'kon'),
('mrożonki', 'Lublin', 'Krosno', 'term', 'rej', 'wymaga oczenikania', 'prac', '279', 'kon'),
('AGD', 'Stargard', 'Katowice', 'term', 'rej', '', 'prac', '280', 'kon'),
('AGD', 'Katowice', 'Glogów', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '281', 'kon'),
('warzywa', 'Starachowice', 'Katowice', 'term', 'rej', '', 'prac', '282', 'kon'),
('sprzęt budowlany', 'Ruda Śląska', 'Jaworzno', 'term', 'rej', 'wymaga oczenikania', 'prac', '283', 'kon'),
('RTV', 'Ruda Śląska', 'Sosnowiec', 'term', 'rej', '', 'prac', '284', 'kon'),
('napoje', 'Sosnowiec', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '285', 'kon'),
('mrożonki', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '286', 'kon'),
('AGD', 'Gliwice', 'Siemianowice Śląskie', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '287', 'kon'),
('RTV', 'Sosnowiec', 'Elk', 'term', 'rej', '', 'prac', '288', 'kon'),
('alkochol', 'Katowice', 'Pruszków', 'term', 'rej', 'przewóz specialny', 'prac', '289', 'kon'),
('napoje', 'Walbrzych', 'Kędzierzyn-Koźle', 'term', 'rej', '', 'prac', '290', 'kon'),
('RTV', 'Siemianowice Śląskie', 'lódź', 'term', 'rej', '', 'prac', '291', 'kon'),
('części do maszyn budowlanych', 'Gliwice', 'Piotrków', 'term', 'rej', 'wymaga oczenikania', 'prac', '292', 'kon'),
('sprzęt budowlany', 'Katowice', 'Sosnowiec', 'term', 'rej', '', 'prac', '293', 'kon'),
('drewno', 'Gliwice', 'lódź', 'term', 'rej', '', 'prac', '294', 'kon'),
('melale przemysłowe', 'Katowice', 'Tomaszów Mazowiecki', 'term', 'rej', 'wymaga oczenikania', 'prac', '295', 'kon'),
('warzywa', 'Będzin', 'Kielce', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '296', 'kon'),
('AGD', 'Katowice', 'Gliwice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '297', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Siemianowice Śląskie', 'Ruda Śląska', 'term', 'rej', 'wymaga oczenikania', 'prac', '298', 'kon'),
('melale przemysłowe', 'Świętochlowice', 'Katowice', 'term', 'rej', '', 'prac', '299', 'kon'),
('drewno', 'Rybnik', 'Jaworzno', 'term', 'rej', '', 'prac', '300', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Koszalin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '301', 'kon'),
('części samolotowe', 'Ruda Śląska', 'Sosnowiec', 'term', 'rej', '', 'prac', '302', 'kon'),
('mrożonki', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '303', 'kon'),
('papier', 'Katowice', 'Bielsko-Biala', 'term', 'rej', 'wymaga oczenikania', 'prac', '304', 'kon'),
('szkło', 'Tychy', 'Jaworzno', 'term', 'rej', 'wymaga oczenikania', 'prac', '305', 'kon'),
('części samolotowe', 'Sosnowiec', 'Kolobrzeg', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '306', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Ruda Śląska', 'Świętochlowice', 'term', 'rej', '', 'prac', '307', 'kon'),
('drewno', 'Slupsk', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '308', 'kon'),
('szkło', 'Jaworzno', 'Katowice', 'term', 'rej', '', 'prac', '309', 'kon'),
('alkochol', 'Skierniewice', 'Zielona Góra', 'term', 'rej', '', 'prac', '310', 'kon'),
('części samochodowe', 'Ruda Śląska', 'Sosnowiec', 'term', 'rej', '', 'prac', '311', 'kon'),
('papier', 'Gliwice', 'Bialystok', 'term', 'rej', '', 'prac', '312', 'kon'),
('szkło', 'Ruda Śląska', 'Kędzierzyn-Koźle', 'term', 'rej', 'wymaga oczenikania', 'prac', '313', 'kon'),
('części samochodowe', 'Belchatów', 'Katowice', 'term', 'rej', '', 'prac', '314', 'kon'),
('warzywa', 'Jaworzno', 'Gniezno', 'term', 'rej', 'przewóz specialny', 'prac', '315', 'kon'),
('AGD', 'Dębica', 'Nowy Sącz', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '316', 'kon'),
('melale przemysłowe', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '317', 'kon'),
('mrożonki', 'Olsztyn', 'Gliwice', 'term', 'rej', 'przewóz specialny', 'prac', '318', 'kon'),
('mrożonki', 'Ruda Śląska', 'Krosno', 'term', 'rej', '', 'prac', '319', 'kon'),
('części samolotowe', 'Stalowa Wola', 'Sosnowiec', 'term', 'rej', '', 'prac', '320', 'kon'),
('szkło', 'Jaworzno', 'Lomża', 'term', 'rej', 'wymaga oczenikania', 'prac', '321', 'kon'),
('części samochodowe', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '322', 'kon'),
('szkło', 'Myslowice', 'Stalowa Wola', 'term', 'rej', 'wymaga oczenikania', 'prac', '323', 'kon'),
('drewno', 'Starogard Gdański', 'Ruda Śląska', 'term', 'rej', '', 'prac', '324', 'kon'),
('sprzęt budowlany', 'Tarnowskie Góry', 'Ostrowiec Świętokrzyski', 'term', 'rej', '', 'prac', '325', 'kon'),
('papier', 'Starachowice', 'Katowice', 'term', 'rej', '', 'prac', '326', 'kon'),
('warzywa', 'Gliwice', 'Tychy', 'term', 'rej', '', 'prac', '327', 'kon'),
('części do maszyn budowlanych', 'Jaworzno', 'Sosnowiec', 'term', 'rej', '', 'prac', '328', 'kon'),
('napoje', 'Ruda Śląska', 'Kraków', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '329', 'kon'),
('warzywa', 'Szczecin', 'Koszalin', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '330', 'kon'),
('plastiki', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '331', 'kon'),
('AGD', 'Jaworzno', 'Sosnowiec', 'term', 'rej', '', 'prac', '332', 'kon'),
('plastiki', 'Katowice', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '333', 'kon'),
('mrożonki', 'Nowy Sącz', 'Chorzów', 'term', 'rej', '', 'prac', '334', 'kon'),
('melale przemysłowe', 'Ostrów', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '335', 'kon'),
('części do maszyn budowlanych', 'Siemianowice Śląskie', 'Nowy Sącz', 'term', 'rej', '', 'prac', '336', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '337', 'kon'),
('plastiki', 'Chorzów', 'Jaworzno', 'term', 'rej', 'wymaga oczenikania', 'prac', '338', 'kon'),
('alkochol', 'Stalowa Wola', 'Chorzów', 'term', 'rej', 'wymaga oczenikania', 'prac', '339', 'kon'),
('alkochol', 'Tczew', 'Ruda Śląska', 'term', 'rej', 'przewóz specialny', 'prac', '340', 'kon'),
('części samolotowe', 'Gliwice', 'Gliwice', 'term', 'rej', 'wymaga oczenikania', 'prac', '341', 'kon'),
('części samochodowe', 'Katowice', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '342', 'kon'),
('części do maszyn budowlanych', 'Ruda Śląska', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '343', 'kon'),
('RTV', 'Katowice', 'Kolobrzeg', 'term', 'rej', '', 'prac', '344', 'kon'),
('napoje', 'Siemianowice Śląskie', 'Skierniewice', 'term', 'rej', '', 'prac', '345', 'kon'),
('napoje', 'Koszalin', 'Katowice', 'term', 'rej', '', 'prac', '346', 'kon'),
('szkło', 'Katowice', 'Biala Podlaska', 'term', 'rej', '', 'prac', '347', 'kon'),
('mrożonki', 'Starogard Gdański', 'Katowice', 'term', 'rej', '', 'prac', '348', 'kon'),
('drewno', 'Poznań', 'Gliwice', 'term', 'rej', 'przewóz specialny', 'prac', '349', 'kon'),
('melale przemysłowe', 'Rumia', 'Warszawa', 'term', 'rej', '', 'prac', '350', 'kon'),
('napoje', 'Jaworzno', 'Chelm', 'term', 'rej', 'przewóz specialny', 'prac', '351', 'kon'),
('części samolotowe', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '352', 'kon'),
('części samochodowe', 'Gliwice', 'Sosnowiec', 'term', 'rej', 'przewóz specialny', 'prac', '353', 'kon'),
('części do maszyn budowlanych', 'Ruda Śląska', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '354', 'kon'),
('drewno', 'Warszawa', 'Częstochowa', 'term', 'rej', 'wymaga oczenikania', 'prac', '355', 'kon'),
('alkochol', 'Pulawy', 'Ruda Śląska', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '356', 'kon'),
('drewno', 'Dębica', 'Katowice', 'term', 'rej', 'przewóz specialny', 'prac', '357', 'kon'),
('papier', 'Ruda Śląska', 'Siemianowice Śląskie', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '358', 'kon'),
('sprzęt budowlany', 'Myslowice', 'Konin', 'term', 'rej', 'wymaga oczenikania', 'prac', '359', 'kon'),
('sprzęt budowlany', 'Jelenia Góra', 'Sosnowiec', 'term', 'rej', '', 'prac', '360', 'kon'),
('części samochodowe', 'Suwalki', 'Gliwice', 'term', 'rej', 'wymaga oczenikania', 'prac', '361', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Glogów', 'Grudziądz', 'term', 'rej', 'wymaga oczenikania', 'prac', '362', 'kon'),
('części do maszyn budowlanych', 'Rumia', 'Sosnowiec', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '363', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Pulawy', 'term', 'rej', '', 'prac', '364', 'kon'),
('warzywa', 'Zgierz', 'Radom', 'term', 'rej', '', 'prac', '365', 'kon'),
('części samolotowe', 'Jelenia Góra', 'Zabrze', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '366', 'kon'),
('AGD', 'Kędzierzyn-Koźle', 'Jaworzno', 'term', 'rej', '', 'prac', '367', 'kon'),
('sprzęt budowlany', 'Ruda Śląska', 'Jastrzębie-Zdrój', 'term', 'rej', 'przewóz specialny', 'prac', '368', 'kon'),
('papier', 'lódź', 'Zawiercie', 'term', 'rej', '', 'prac', '369', 'kon'),
('AGD', 'Leszno', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '370', 'kon'),
('melale przemysłowe', 'Zielona Góra', 'Jaworzno', 'term', 'rej', 'wymaga oczenikania', 'prac', '371', 'kon'),
('warzywa', 'Gliwice', 'Inowroclaw', 'term', 'rej', '', 'prac', '372', 'kon'),
('sprzęt budowlany', 'Gliwice', 'Ruda Śląska', 'term', 'rej', '', 'prac', '373', 'kon'),
('melale przemysłowe', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '374', 'kon'),
('napoje', 'Dębica', 'Katowice', 'term', 'rej', '', 'prac', '375', 'kon'),
('mrożonki', 'Gliwice', 'Dębica', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '376', 'kon'),
('alkochol', 'Siemianowice Śląskie', 'Myslowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '377', 'kon'),
('alkochol', 'Bielsko-Biala', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '378', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Leszno', 'Jaworzno', 'term', 'rej', '', 'prac', '379', 'kon'),
('mrożonki', 'Jaworzno', 'Katowice', 'term', 'rej', '', 'prac', '380', 'kon'),
('warzywa', 'Katowice', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '381', 'kon'),
('plastiki', 'Chelm', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '382', 'kon'),
('sprzęt budowlany', 'Siemianowice Śląskie', 'Katowice', 'term', 'rej', '', 'prac', '383', 'kon'),
('papier', 'Bielsko-Biala', 'Gliwice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '384', 'kon'),
('szkło', 'Katowice', 'Ruda Śląska', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '385', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Katowice', 'Sosnowiec', 'term', 'rej', '', 'prac', '386', 'kon'),
('AGD', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '387', 'kon'),
('RTV', 'Jaworzno', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '388', 'kon'),
('sprzęt budowlany', 'Mielec', 'Slupsk', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '389', 'kon'),
('plastiki', 'Legnica', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '390', 'kon'),
('papier', 'Gdynia', 'Tarnowskie Góry', 'term', 'rej', 'przewóz specialny', 'prac', '391', 'kon'),
('drewno', 'Katowice', 'Grudziądz', 'term', 'rej', '', 'prac', '392', 'kon'),
('szkło', 'Nowy Sącz', 'Katowice', 'term', 'rej', '', 'prac', '393', 'kon'),
('mrożonki', 'Kędzierzyn-Koźle', 'Elbląg', 'term', 'rej', '', 'prac', '394', 'kon'),
('sprzęt budowlany', 'Katowice', 'Siemianowice Śląskie', 'term', 'rej', 'wymaga oczenikania', 'prac', '395', 'kon'),
('AGD', 'Rybnik', 'Świdnica', 'term', 'rej', '', 'prac', '396', 'kon'),
('papier', 'Ruda Śląska', 'Zamość', 'term', 'rej', '', 'prac', '397', 'kon'),
('papier', 'Gliwice', 'Bialystok', 'term', 'rej', '', 'prac', '398', 'kon'),
('papier', 'Katowice', 'Jaworzno', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '399', 'kon'),
('drewno', 'Siemianowice Śląskie', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '400', 'kon'),
('AGD', 'Kolobrzeg', 'Katowice', 'term', 'rej', '', 'prac', '401', 'kon'),
('szkło', 'Katowice', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '402', 'kon'),
('alkochol', 'Jaworzno', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '403', 'kon'),
('części samochodowe', 'Jaworzno', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '404', 'kon'),
('napoje', 'Nowy Sącz', 'Ostrów', 'term', 'rej', 'wymaga oczenikania', 'prac', '405', 'kon'),
('napoje', 'Glogów', 'Ruda Śląska', 'term', 'rej', '', 'prac', '406', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Sosnowiec', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '407', 'kon'),
('drewno', 'Katowice', 'Przemyśl', 'term', 'rej', '', 'prac', '408', 'kon'),
('mrożonki', 'Gliwice', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '409', 'kon'),
('alkochol', 'Szczecin', 'Jaworzno', 'term', 'rej', '', 'prac', '410', 'kon'),
('części samochodowe', 'Racibórz', 'Ruda Śląska', 'term', 'rej', '', 'prac', '411', 'kon'),
('drewno', 'Katowice', 'Gdańsk', 'term', 'rej', '', 'prac', '412', 'kon'),
('alkochol', 'Rzeszów', 'Szczecin', 'term', 'rej', 'przewóz specialny', 'prac', '413', 'kon'),
('części samolotowe', 'Sosnowiec', 'Lublin', 'term', 'rej', 'wymaga oczenikania', 'prac', '414', 'kon'),
('szkło', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '415', 'kon'),
('części samolotowe', 'Jaworzno', 'Jaworzno', 'term', 'rej', '', 'prac', '416', 'kon'),
('sprzęt budowlany', 'Katowice', 'Konin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '417', 'kon'),
('szkło', 'Katowice', 'Kolobrzeg', 'term', 'rej', '', 'prac', '418', 'kon'),
('części samolotowe', 'Katowice', 'Legionowo', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '419', 'kon'),
('drewno', 'Gliwice', 'Tczew', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '420', 'kon'),
('alkochol', 'Katowice', 'Jaworzno', 'term', 'rej', '', 'prac', '421', 'kon'),
('warzywa', 'Gliwice', 'Rumia', 'term', 'rej', 'wymaga oczenikania', 'prac', '422', 'kon'),
('napoje', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '423', 'kon'),
('części samochodowe', 'Rybnik', 'Plock', 'term', 'rej', '', 'prac', '424', 'kon'),
('drewno', 'Gliwice', 'Sosnowiec', 'term', 'rej', '', 'prac', '425', 'kon'),
('RTV', 'Plock', 'Walbrzych', 'term', 'rej', '', 'prac', '426', 'kon'),
('napoje', 'Jastrzębie-Zdrój', 'Ruda Śląska', 'term', 'rej', '', 'prac', '427', 'kon'),
('melale przemysłowe', 'Wloclawek', 'Elbląg', 'term', 'rej', '', 'prac', '428', 'kon'),
('drewno', 'Siemianowice Śląskie', 'Piaseczno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '429', 'kon'),
('plastiki', 'Siemianowice Śląskie', 'Wroclaw', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '430', 'kon'),
('drewno', 'Starachowice', 'Katowice', 'term', 'rej', '', 'prac', '431', 'kon'),
('części samolotowe', 'Gniezno', 'Ruda Śląska', 'term', 'rej', '', 'prac', '432', 'kon'),
('AGD', 'Nowy Sącz', 'Katowice', 'term', 'rej', '', 'prac', '433', 'kon'),
('części samolotowe', 'Stalowa Wola', 'Tczew', 'term', 'rej', 'wymaga oczenikania', 'prac', '434', 'kon'),
('RTV', 'Opole', 'Ruda Śląska', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '435', 'kon'),
('części do maszyn budowlanych', 'Lublin', 'Gliwice', 'term', 'rej', 'wymaga oczenikania', 'prac', '436', 'kon'),
('części samochodowe', 'Bydgoszcz', 'Gdańsk', 'term', 'rej', '', 'prac', '437', 'kon'),
('szkło', 'Jaworzno', 'Katowice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '438', 'kon'),
('napoje', 'Świętochlowice', 'Siemianowice Śląskie', 'term', 'rej', '', 'prac', '439', 'kon'),
('szkło', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '440', 'kon'),
('warzywa', 'Będzin', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '441', 'kon'),
('napoje', 'Piotrków', 'Katowice', 'term', 'rej', '', 'prac', '442', 'kon'),
('części do maszyn budowlanych', 'Sosnowiec', 'Gliwice', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '443', 'kon'),
('alkochol', 'Wloclawek', 'Ruda Śląska', 'term', 'rej', '', 'prac', '444', 'kon'),
('RTV', 'Gliwice', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '445', 'kon'),
('papier', 'Ruda Śląska', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '446', 'kon'),
('szkło', 'Siemianowice Śląskie', 'Ruda Śląska', 'term', 'rej', '', 'prac', '447', 'kon'),
('części samolotowe', 'Sosnowiec', 'Katowice', 'term', 'rej', '', 'prac', '448', 'kon'),
('szkło', 'Zgierz', 'Katowice', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '449', 'kon'),
('papier', 'Piotrków', 'Gliwice', 'term', 'rej', '', 'prac', '450', 'kon'),
('plastiki', 'Jaworzno', 'Katowice', 'term', 'rej', '', 'prac', '451', 'kon'),
('drewno', 'Elk', 'Katowice', 'term', 'rej', 'wymaga oczenikania', 'prac', '452', 'kon'),
('melale przemysłowe', 'Jaworzno', 'Katowice', 'term', 'rej', 'przejazd z mandatem karnym', 'prac', '453', 'kon'),
('alkochol', 'Katowice', 'Tczew', 'term', 'rej', 'wymaga oczenikania', 'prac', '454', 'kon'),
('sprzęt budowlany', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '455', 'kon'),
('alkochol', 'Ostrolęka', 'Sosnowiec', 'term', 'rej', 'wymaga oczenikania', 'prac', '456', 'kon'),
('części samolotowe', 'Gliwice', 'Starogard Gdański', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '457', 'kon'),
('napoje', 'Ruda Śląska', 'Ruda Śląska', 'term', 'rej', '', 'prac', '458', 'kon'),
('plastiki', 'Katowice', 'Kraków', 'term', 'rej', '', 'prac', '459', 'kon'),
('melale przemysłowe', 'Biala Podlaska', 'Jastrzębie-Zdrój', 'term', 'rej', '', 'prac', '460', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Jaworzno', 'Konin', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '461', 'kon'),
('drewno', 'Katowice', 'Glogów', 'term', 'rej', '', 'prac', '462', 'kon'),
('części samolotowe', 'Tychy', 'Katowice', 'term', 'rej', '', 'prac', '463', 'kon'),
('szkło', 'Żory', 'Pruszków', 'term', 'rej', '', 'prac', '464', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '465', 'kon'),
('części do maszyn budowlanych', 'Gniezno', 'Ruda Śląska', 'term', 'rej', '', 'prac', '466', 'kon'),
('warzywa', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '467', 'kon'),
('mrożonki', 'Chelm', 'Sosnowiec', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '468', 'kon'),
('PDK (produkty dużej komsumpcji)', 'Jaworzno', 'Piekary Śląskie', 'term', 'rej', '', 'prac', '469', 'kon'),
('drewno', 'Pruszków', 'Zabrze', 'term', 'rej', '', 'prac', '470', 'kon'),
('AGD', 'Grudziądz', 'Gliwice', 'term', 'rej', 'wymaga oczenikania', 'prac', '471', 'kon'),
('napoje', 'Katowice', 'Sosnowiec', 'term', 'rej', '', 'prac', '472', 'kon'),
('alkochol', 'Starachowice', 'Jaworzno', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '473', 'kon'),
('papier', 'Żory', 'Siedlce', 'term', 'rej', '', 'prac', '474', 'kon'),
('drewno', 'Tomaszów Mazowiecki', 'Sosnowiec', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '475', 'kon'),
('mrożonki', 'Jaworzno', 'Katowice', 'term', 'rej', '', 'prac', '476', 'kon'),
('drewno', 'Gdynia', 'Jaworzno', 'term', 'rej', '', 'prac', '477', 'kon'),
('części do maszyn budowlanych', 'Sosnowiec', 'Kędzierzyn-Koźle', 'term', 'rej', '', 'prac', '478', 'kon'),
('części samolotowe', 'Gdynia', 'Katowice', 'term', 'rej', '', 'prac', '479', 'kon'),
('melale przemysłowe', 'Jaworzno', 'Ruda Śląska', 'term', 'rej', '', 'prac', '480', 'kon'),
('części do maszyn budowlanych', 'Racibórz', 'Chelm', 'term', 'rej', '', 'prac', '481', 'kon'),
('warzywa', 'Gliwice', 'Katowice', 'term', 'rej', '', 'prac', '482', 'kon'),
('części do maszyn budowlanych', 'lódź', 'Gliwice', 'term', 'rej', '', 'prac', '483', 'kon'),
('AGD', 'Bielsko-Biala', 'Glogów', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '484', 'kon'),
('napoje', 'Katowice', 'Ruda Śląska', 'term', 'rej', '', 'prac', '485', 'kon'),
('melale przemysłowe', 'Ruda Śląska', 'Katowice', 'term', 'rej', '', 'prac', '486', 'kon'),
('mrożonki', 'Katowice', 'Biala Podlaska', 'term', 'rej', 'przewóz specialny', 'prac', '487', 'kon'),
('AGD', 'Bielsko-Biala', 'Ruda Śląska', 'term', 'rej', 'przewóz specialny', 'prac', '488', 'kon'),
('alkochol', 'Katowice', 'Katowice', 'term', 'rej', '', 'prac', '489', 'kon'),
('części samochodowe', 'Katowice', 'Poznań', 'term', 'rej', '', 'prac', '490', 'kon'),
('mrożonki', 'Pruszków', 'Ostrolęka', 'term', 'rej', 'przejazd skontorlowany przez inspekcje', 'prac', '491', 'kon'),
('części do maszyn budowlanych', 'Ruda Śląska', 'Piaseczno', 'term', 'rej', 'wymaga oczenikania', 'prac', '492', 'kon'),
('szkło', 'Sosnowiec', 'Ostrolęka', 'term', 'rej', '', 'prac', '493', 'kon'),
('warzywa', 'Rybnik', 'Jaworzno', 'term', 'rej', 'zlecenie piorytetowe', 'prac', '494', 'kon'),
('papier', 'Lomża', 'Katowice', 'term', 'rej', '', 'prac', '495', 'kon'),
('szkło', 'Jaworzno', 'Katowice', 'term', 'rej', 'przewóz specialny', 'prac', '496', 'kon'),
('RTV', 'Elk', 'Katowice', 'term', 'rej', '', 'prac', '497', 'kon'),
('napoje', 'Plock', 'Katowice', 'term', 'rej', '', 'prac', '498', 'kon'),
('warzywa', 'Jaworzno', 'Warszawa', 'term', 'rej', '', 'prac', '499', 'kon');